name: CI
on: workflow_call

jobs:
  Build:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Generate github token
        id: generate_token
        uses: tibdex/github-app-token@v1.8.0 # リリース時にコミットハッシュで固定
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          token: ${{ steps.generate_token.outputs.token }}
      - name: Setup asdf
        uses: asdf-vm/actions/setup@v2
        # 2回目以降エラーが出るが問題なし
        continue-on-error: true
      - name: asdf install
        uses: asdf-vm/actions/install@v2
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build
        run: yarn build

  Lint:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Generate github token
        id: generate_token
        uses: tibdex/github-app-token@v1.8.0 # リリース時にコミットハッシュで固定
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          token: ${{ steps.generate_token.outputs.token }}
      - name: Setup asdf
        uses: asdf-vm/actions/setup@v2
        # 2回目以降エラーが出るが問題なし
        continue-on-error: true
      - name: asdf install
        uses: asdf-vm/actions/install@v2
      - name: Install dependencies
        run: yarn install --immutable
      - name: Lint
        run: yarn lint

  Test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Generate github token
        id: generate_token
        uses: tibdex/github-app-token@v1.8.0 # リリース時にコミットハッシュで固定
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          token: ${{ steps.generate_token.outputs.token }}
      - name: Setup asdf
        uses: asdf-vm/actions/setup@v2
        # 2回目以降エラーが出るが問題なし
        continue-on-error: true
      - name: asdf install
        uses: asdf-vm/actions/install@v2
      - name: Install dependencies
        run: yarn install --immutable
      - name: test
        run: yarn test:coverage --reporter=default --reporter=vitest-github-actions-reporter
        env:
          TZ: Asia/Tokyo
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: coverage
          path: coverage/
          retention-days: 3
