name: Cloudflare Pages Frontend Deploy

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches:
      - main

jobs:
  Publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup asdf
        uses: asdf-vm/actions/setup@v2
        # 2回目以降エラーが出るが問題なし
        continue-on-error: true
      - name: asdf install
        uses: asdf-vm/actions/install@v2
      - name: Install dependencies
        run: yarn install --immutable
      - name: Generate github token
        id: generate_token
        uses: tibdex/github-app-token@v1.8.0 # リリース時にコミットハッシュで固定
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          projectName: qa-artist
          directory: ./dist
